### ISSUE TITLE
Jumping popup-menu

### ISSUE THREAD

**Issue by JanLoebel** [KohheePeace/slate-tuto#1]
Hi there, thank you for this great repository :) I'm sorry to hear that the documents weren't saved correctly. I hope you'll find the power to write the tutorial again.

I've one small problem when using your editor. The popup-menu is jumping after selecting an action, see the attached gif:

![slate-tuto](https://user-images.githubusercontent.com/1765067/41101953-e82486e4-6a65-11e8-878e-08149c88b2d6.gif)

**Comment by kohheepeace** [comment]
@JanLoebel  Thank you for reporting and sorry for late reply!

![hoge](https://media.giphy.com/media/5h9xjUGjbnFUGnIyDJ/giphy.gif)

1. From my browser "chrome", the popup menu vanishes after click.
The popup menu position is calculated by the below code.
https://github.com/KohheePeace/slate-tuto/blob/master/src/slate-editor/helpers/updateHoverMenuPosition.js

I referenced it from below
https://github.com/ianstormtaylor/slate/tree/master/examples/hovering-menu

I'm pleasure if you detect how to fix this !!

2. Strikethrough in popup menu is not working. Thank you for your gif.

3. I'm not regaining the power to re write tutorial yet. And also I'm not familiar with "slatejs" 😓 If you desire let me know!

**Comment by JanLoebel** [comment]
No problem :) Don't worry! Currently, I'm also very busy with a lot of other projects, but I will write it down and if I will find some time I will definitely have a look at the problem.

**Comment by kohheepeace** [comment]
This can be fixed by `componentDidUpdate`
