### ISSUE TITLE
Need to install @material-ui/core

### ISSUE THREAD

**Issue by erichartline** [KohheePeace/slate-tuto#4]
Hello, thanks for this helpful app! I don't know if anyone else has run into this issue, but I was unable to start this app without installing `@material-ui/core` as well. It looks like there was a problem with `@material-ui/icons` needing the core package as a dependency. After installing this, it worked great.

**Comment by kohheepeace** [comment]
@wildlifehexagon It is because the "material-ui" version is changed. Anyway thanks for reporting 😄
